export const REG_USER_REQUESTED = 'REG_USER_REQUESTED';
export const REG_USER_SUCCESS = 'REG_USER_SUCCESS';
export const REG_USER_FAILED = 'REG_USER_FAILED';

export const LOG_USER_REQUESTED = 'LOG_USER_REQUESTED';
export const LOG_USER_SUCCESS = 'LOG_USER_SUCCESS';
export const LOG_USER_FAILED = 'LOG_USER_FAILED';

export const USER_DATA_REQUIRED = 'USER_DATA_REQUIRED';
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';
export const USER_DATA_FAILED = 'USER_DATA_FAILED';

export const USER_TODOS_REQUESTED = 'USER_TODOS_REQUESTED';
export const USER_TODOS_SUCCESS = 'USER_TODOS_SUCCESS';
export const USER_TODOS_FAILED = 'USER_TODOS_FAILED';

export const CREATE_TODO_REQUESTED = 'CREATE_TODO_REQUESTED';
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';
export const CREATE_TODO_FAILED = 'CREATE_TODO_FAILED';

export const DELETE_TODO_REQUESTED = 'DELETE_TODO_REQUESTED';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAILED = 'DELETE_TODO_FAILED';

export const EDIT_TODO_REQUESTED = 'EDIT_TODO_REQUESTED';
export const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS';
export const EDIT_TODO_FAILED = 'EDIT_TODO_FAILED';